### ISSUE TITLE
Gear Height in "gear_parameters"

### ISSUE THREAD

**Issue by TheFattestUnicorn** [Alonso-JAMM/planetary_gears#1]
Can you please add the possibility to change the gear height in the "gear_parameters" panel? It works by manually change the setting on each involute gear, but it would be more convenient to do it there.  I would do it myself but i'm not that experienced in python.

**Comment by Alonso-JAMM** [comment]
I chose to keep the gear height parameter separated into each individual gear because in my use-case I have ring gears slightly taller than the planets and sun. However, now I think a property in "gear_parameters" to set the gears heights may be possible without breaking my use-case of gears of different heights. 

I will add this option.
